name: push
on:
  push:
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v18.12.0
      uses: actions/setup-node@v1
      with:
        node-version: '18.12.0'
    - name: echo
      run: echo "test"
