name: workflow_dispatch
 
on:
  workflow_dispatch:
env:
  exe_env : gcp-test-deploy-release
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: git setting
      run: echo "test"
